# Add/remove 'critical' label if issue contains the words 'urgent' or 'critical'
critical:
    - '(critical|urgent)'

# Add/remove 'bug' label if issue contains the word 'bug report'
"🐛 bug":
    - '(bug report)'
